### ISSUE TITLE
Error on example server/client rpc call

### ISSUE THREAD

**Issue by ruddy17** [aaiyer/rfoo#2]
I create 2 files, rfoo_server.py:
`import rfoo`
`class MyHandler(rfoo.BaseHandler):`
`    def echo(self, str):`
`        return str`
`rfoo.UnixServer(MyHandler).start('sock')`

and rfoo_client.py:

`import rfoo`
`from rfoo import Proxy`
`c = rfoo.UnixConnection().connect('sock')`
`print(Proxy(c).echo('hello'))`

Then I start them one after another and expect the client to print hello. Instead I get IOError in server, and EOFError on client (due to no response from server obviously).

I found out exact reason of this error (sorry for not making a pull request):

lines 251:252 of _rfoo.py
`if buffer[0] != INTEGER:`
`raise IOError()`

when I comment them out, everything works OK, and I can't get what they are there for.

**Comment by aaiyer** [comment]
The condition checks if the first value from the server is an 'i'
You are most likely starting the client and then the server. Therefore the first character from the Unix Socket is probably an EOF.

**Comment by ruddy17** [comment]
Well, no. I start the server first, for sure. Also, I searched and couldn’t find any place where ‘i’ is appended to the message before sending to socket.

**Comment by aaiyer** [comment]
This has been fixed with pull https://github.com/aaiyer/rfoo/pull/4

**Comment by Frostbite22** [comment]
STill the same issue
