### ISSUE TITLE
Tag release 1.3.1

### ISSUE THREAD

**Issue by kif** [aaiyer/rfoo#9]
Hi,

Now that rfoo works out of the box on Python3, it would be nice to have the debian package upgraded to. Unless it will be removed from debian in a near future.

I made a first attempt of packaging here:
https://salsa.debian.org/kieffer-guest/rfoo
but it fails as the release is not tagged in github. So could you please create a tag called 1.3.1 to allow the packaging ?

Thanks in advance.

Jérôme
PS: The debian developper is in copy @picca

**Comment by aaiyer** [comment]
1.3.1 tag has been created.
